name: Pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - uses: iterative/setup-dvc@v1
  
      - name: Pull data with DVC
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: |
          dvc pull

      - name: Preprocessing with Pytest
        run: pytest src/test/preprocessing_test.py

      - name: Training_test with Pytest
        run: pytest src/test/training_test.py

      - name: Compare_test with Pytest
        run: pytest src/test/compare_test.py